#!/bin/bash

echo -n "Enter your username: "
read username

wget -P /home/$username/selfvpn-client/ https://git.io/vpn -O openvpn-install.sh
sed -i "s/read -N 999999 -t 0.001/#read -N 999999 -t 0.001/" openvpn-install.sh

sudo chmod +x openvpn-install.sh
sudo chmod +x client.py

sudo ./openvpn-install.sh

sed -i "s/10 120/5 10/" /etc/openvpn/server/server.conf

echo "[Unit]
Description=auto
After=network.target

[Service]
User=root
Type=simple
ExecStart=/home/$username/selfvpn-client/client.py
Restart=always

[Install]
WantedBy=multi-user.target" > selfpn.service
sudo mv selfvpn.service /lib/systemd/system/
sudo chmod 644 /lib/systemd/system/selfvpn.service

sudo python3 client.py

sudo systemctl daemon-reload
sudo systemctl start selfvpn.service
sudo systemctl enable selfvpn.service
#sudo systemctl status serlfvpn.service
